# Generated by Django 2.1.5 on 2019-01-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
